import accounts from './accounts'
import accounting from './accounting'
import cafeteria from './cafeteria'
import configurations from './configurations'
import doctor from './doctor'
import frontdesk from './front-desk'
import hmoMgt from './hmo-mgt'
import humanResources from './human-resources'
import medicalLab from './medical-lab'
import nurse from './nurse'
import paypoint from './paypoint'
import pharmacy from './pharmacy'
import plan from './plan'
import procedure from './procedure'
import radiology from './radiology'
import reports from './reports'
import store from './store'

export default [...frontdesk, ...medicalLab, ...paypoint, ...pharmacy, ...radiology, ...procedure, ...nurse, ...doctor, ...humanResources, ...plan, ...store, ...cafeteria, ...hmoMgt, ...accounting, ...reports, ...configurations, ...accounts]
